services:
  frontend:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    ports:
      - 4321:4321
      - 9323:9323
