name: Lint and Prettier Check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: コードをチェックアウト
        uses: actions/checkout@v4

      - name: Node.jsをセットアップ
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: pnpmをインストール
        run: npm install -g pnpm

      - name: 依存関係をインストール
        run: pnpm install

      - name: ESLintによる静的解析
        run: pnpm run lint

      - name: Prettierによるフォーマットチェック
        run: pnpm run format:check
